### ISSUE TITLE
Prepare Release 20.10

### ISSUE THREAD

**Issue by janmayer** [janmayer/hdtv#10]
TODOs:
- [x] Regression: Page Up / Page Down does not recall previous commands starting with a given part of a command
- [x] Improvement: Increase Contrast in Bright Mode: Line Colors are too light.
- [ ] Fix possible problem mentioned in [test_cmd_fit_peakfind](https://github.com/janmayer/hdtv/blob/200b0706a68f0755d7d87770ba0b952899bfdd18/tests/plugins/test_fitInterface.py#L101)
- [x] Test more ROOT versions
- [x] Update Readme
- [x] Update changelog

Nice-to-haves:
- [ ] Documentation: Start detailed documentation / user guide with latest developments
    - [ ] Background Models (Examples, Use-Cases)
    - [ ] Calbin changes
- [x] Enforce source code formatting 
    - [x] clang-format
    - [x] cmake-format
    - [x] something for python formatting

**Comment by op3** [comment]
> Improvement: Increase Contrast in Bright Mode: Line Colors are too light.

I did a few experiments with the [HSLuv color space](https://www.hsluv.org/), which makes it easier to find colors with the same lightness and uniformly spaced hue.

![new_color_scheme](https://user-images.githubusercontent.com/318752/95227802-d6194500-07fe-11eb-8d11-f9fe07963ccc.png)

The hue of each color should be optimally spaced using the golden angle, and I also added a sin-wave to the luminance for additional contrast.

This would allow us to use the same colors for the light and dark mode. Only the color of the active spectrum is different (The saturation is increased from 94% to 100% and the luminance is decreased/increased for light/dark mode).

Implementation:

```python
def get_color(ID, active=False, dark=True):
    golden_angle = 180 * (3 - math.sqrt(5))
    hue = (ID * golden_angle) % 360
    luminance = 50 + 15 * math.sin(ID * math.pi / 5)
    saturation = 100 if active else 94
    if active:
        luminance += 10 if dark else -10
    return hsluv_to_rgb([hue, saturation, luminance])
```

I would like to avoid an additional dependency on [https://github.com/hsluv/hsluv-python](hsluv-python), so we would either have to include part of it in the repository (the implementation is MIT-licensed) or implement it ourselves.

**Comment by janmayer** [comment]
Good Idea 👍 . hsluv-python ist just a single file under MIT License, we could just commit it to the project.

Sorry, I can't really tell from the picture: Is the difference between active and inactive colors large enough to tell them apart when several overlapping spectra are loaded?

**Comment by janmayer** [comment]
v20.10 is released
