### ISSUE TITLE
Issue when running the docker container 

### ISSUE THREAD

**Issue by m-ballu** [janmayer/hdtv#31]
Hello, 

I have an issue when I try using hdtv with docker. The image is constructing fine but when I try to run it with the command 

`docker run -e DISPLAY=${DISPLAY} -v $(pwd):/work -it hdtv`

I get a segmentation violation from cppyy. The stack trace seems to indicate an issue with libcppyy or python. Is that something that have already been raised ? 
I have not tried on another pc yet just to make sure it is not coming from my configuration.

 I'm using docker 23.0.1 with ubuntu 22.04. 

The full stack trace : 

*** Break *** segmentation violation
 Generating stack trace...
 0x00007f0720a19cda in HDTV::Display::Viewer::Viewer(unsigned int, unsigned int, char const*) + 0x3a from /root/.cache/hdtv/50988784-62610-0+**unknown/lib/libdisplay.so**
 0x00007f0733538089 in **\<unknown function>**
 0x00007f073db77717 in **\<unknown> from /opt/root/lib/libcppyy_backend3_10.so.6.26**
 0x00007f073db78fa0 in Cppyy::CallConstructor(long, unsigned long, unsigned long, void*) + 0x30 from /opt/root/lib/libcppyy_backend3_10.so.6.26
 0x00007f073dbf5186 in __\<unknown> from /opt/root/lib/libcppyy3_10.so__
 0x00007f073dbf7d48 in CPyCppyy::CPPMethod::ExecuteProtected(void*, long, CPyCppyy::CallContext*) + 0x118 from /opt/root/lib/libcppyy3_10.so
 0x00007f073dbf5c5e in CPyCppyy::CPPMethod::Execute(void*, long, CPyCppyy::CallContext*) + 0x2e from /opt/root/lib/libcppyy3_10.so
 0x00007f073dbf00dd in CPyCppyy::CPPConstructor::Call(CPyCppyy::CPPInstance*&, _object*, _object*, CPyCppyy::CallContext*) + 0x22d from /opt/root/lib/libcppyy3_10.so
 0x00007f073dbfb2e7 in **\<unknown> from /opt/root/lib/libcppyy3_10.so**
 0x000055c438044174 in _PyObject_Call + 0xb4 from /usr/bin/python3
 0x000055c43803fbbb in **\<unknown> from /usr/bin/python3**
 0x000055c43802b77c in _PyObject_MakeTpCall + 0x1fc from /usr/bin/python3
 0x000055c43802448e in _PyEval_EvalFrameDefault + 0x6b4e from /usr/bin/python3
 0x000055c43802a964 in _PyObject_FastCallDictTstate + 0xc4 from /usr/bin/python3
 0x000055c43803f594 in **\<unknown> from /usr/bin/python3**
 0x000055c43802b77c in _PyObject_MakeTpCall + 0x1fc from /usr/bin/python3
 0x000055c438023e39 in _PyEval_EvalFrameDefault + 0x64f9 from /usr/bin/python3
 0x000055c43802a964 in _PyObject_FastCallDictTstate + 0xc4 from /usr/bin/python3
 0x000055c43803f594 in **\<unknown> from /usr/bin/python3**
 0x000055c43802b77c in _PyObject_MakeTpCall + 0x1fc from /usr/bin/python3
 0x000055c43802448e in _PyEval_EvalFrameDefault + 0x6b4e from /usr/bin/python3
 0x000055c43802a964 in _PyObject_FastCallDictTstate + 0xc4 from /usr/bin/python3
 0x000055c43803f594 in **\<unknown> from /usr/bin/python3**
 0x000055c43802b77c in _PyObject_MakeTpCall + 0x1fc from /usr/bin/python3
 0x000055c438023e39 in _PyEval_EvalFrameDefault + 0x64f9 from /usr/bin/python3
 0x000055c4380353ac in _PyFunction_Vectorcall + 0x7c from /usr/bin/python3
 0x000055c43801e005 in _PyEval_EvalFrameDefault + 0x6c5 from /usr/bin/python3
 0x000055c43801a766 in <unknown> from /usr/bin/python3
 0x000055c438112456 in PyEval_EvalCode + 0x86 from /usr/bin/python3
 0x000055c43813ef08 in **\<unknown> from /usr/bin/python3**
 0x000055c438137d5b in **\<unknown> from /usr/bin/python3**
 0x000055c43813ec55 in **\<unknown> from /usr/bin/python3**
 0x000055c43813e138 in _PyRun_SimpleFileObject + 0x1a8 from /usr/bin/python3
 0x000055c43813de33 in _PyRun_AnyFileObject + 0x43 from /usr/bin/python3
 0x000055c43812f0ae in Py_RunMain + 0x2be from /usr/bin/python3
 0x000055c43810534d in Py_BytesMain + 0x2d from /usr/bin/python3
 0x00007f073e415d90 in **\<unknown> from /lib/x86_64-linux-gnu/libc.so.6** 
 0x00007f073e415e40 in __libc_start_main + 0x80 from /lib/x86_64-linux-gnu/libc.so.6
 0x000055c438105245 in _start + 0x25 from /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/hdtv", line 33, in \<module>
    **sys.exit(load_entry_point('hdtv==0+unknown', 'console_scripts', 'hdtv')())**
  File "/work/hdtv/app.py", line 234, in run
    App()
  File "/work/hdtv/app.py", line 131, in __init__
    spectra = hdtv.session.Session()
  File "/work/hdtv/session.py", line 47, in __init__
    self.window = Window()
  File "/work/hdtv/window.py", line 211, in __init__
    self.viewer = ROOT.HDTV.Display.Viewer()
**cppyy.ll.SegmentationViolation:** Viewer::Viewer(unsigned int w = 800, unsigned int h = 400, const char* title = "hdtv") =>
    SegmentationViolation: segfault in C++; program state was reset

**Comment by op3** [comment]
Could you try to add `-v /tmp/.X11-unix:/tmp/.X11-unix` to your docker command? I. e.,

```bash
docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=${DISPLAY} -v $(pwd):/work -it hdtv
```

**Comment by m-ballu** [comment]
Thank you very much, this works ! I just had to run the command `xhost si:localuser:root` before to fix an issue of permission denied with graphical applications.
