### ISSUE TITLE
.spk file format is not readable

### ISSUE THREAD

**Issue by Hachiman512** [janmayer/hdtv#34]
Hello, I am working on some nuclear structure data so I have multiple .spk files which have multiple .spe files in a single .spk file format. I hope you are aware of this type of file format. Can you tell me how can i read those .spk files?

Thanks:)

**Comment by janmayer** [comment]
Hi,

there is a plethora of file types out in the wild - every manufacturer and institute tends to create their own.

If you have some code or program (or the specification of the format) that can open your files, an easy way out can be converting them to plain text.

HDTV infers the plain text format from the number of columns: Either `y`,  `x y`, or `x y e` . Where `x` is the position, `y` are the counts, and `e` are the errors of counts. For example: A text file with one number per line can be read.
